global:
  slack_api_url: https://hooks.slack.com/services/...

route:
  receiver: default
  group_by: [alertname]
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

  routes:
    - receiver: Database
      match:
        team: database

    - receiver: App
      match:
        team: web

receivers:
  - name: default
    slack_configs:
      - channel: "#alertas"
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.title }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

  - name: App
    slack_configs:
      - channel: "#alertas"
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.title }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

  - name: Database
    slack_configs:
      - channel: "#alertas"
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.title }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: [alertname, dev, instance]
