version: '3.8'
name: observabilidade-go

services:
  app:
    container_name: app
    build: .
    ports:
      - 3333:3333
    depends_on:
      - database

  database:
    container_name: postgresql
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=golang
      - POSTGRESQL_PASSWORD=golang
      - POSTGRESQL_DATABASE=postgresql
    volumes:
      - ./products.sql:/docker-entrypoint-initdb.d/products.sql

  db_exporter:
    container_name: pgsql-exporter
    image: bitnami/postgres-exporter
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://golang:golang@database:5432/golang?schema=public
    depends_on:
      - database

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000

  alertmanager:
    container_name: alert-manager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --cluster.advertise-address=0.0.0.0:9093
    depends_on:
      - prometheus
