version: '3.8'

services:
  app:
    build: .
    ports:
      - 3333:3333
    networks:
      metrics:
        ipv4_address: 172.0.0.10
    depends_on:
      - database

  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=golang
      - POSTGRESQL_PASSWORD=golang
      - POSTGRESQL_DATABASE=postgresql
    volumes:
      - ./app/database/products.sql:/docker-entrypoint-initdb.d/products.sql
    networks:
      metrics:
        ipv4_address: 172.0.0.20

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      metrics:
        ipv4_address: 172.0.0.30

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      metrics:
        ipv4_address: 172.0.0.40

networks:
  metrics:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24