version: '3.8'

services:
  app:
    build: .
    ports:
      - 3333:3333
    networks:
      metrics:
        ipv4_address: 172.0.0.10
    depends_on:
      - database

  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=golang
      - POSTGRESQL_PASSWORD=golang
      - POSTGRESQL_DATABASE=postgresql
    volumes:
      - ./products.sql:/docker-entrypoint-initdb.d/products.sql
    networks:
      metrics:
        ipv4_address: 172.0.0.20

  db_exporter:
    image: bitnami/postgres-exporter
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://golang:golang@database:5432/golang?schema=public
    networks:
      - metrics
    depends_on:
      - database

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      metrics:
        ipv4_address: 172.0.0.30

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      metrics:
        ipv4_address: 172.0.0.40

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      metrics:
        ipv4_address: 172.0.0.50
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --cluster.advertise-address=0.0.0.0:9093
    depends_on:
      - prometheus

networks:
  metrics:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24