receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: 0.0.0.0:8889

  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    add_metric_suffixes: true

  otlp:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
    default_labels_enabled:
      exporter: true
      job: true

processors:
  batch:
    # timeout: 1s
    # send_batch_size: 1024

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    logs:
      level: DEBUG

  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, prometheus, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
