management:
  endpoints:
    web:
      exposure:
        include: prometheus

  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: "%boldGreen(%d{dd/MM/yyyy}) - %boldGreen(%d{HH:mm:ss})  %highlight(%-5level) [THREAD] %boldRed(%thread)  [LOGGER] %boldMagenta(%logger{26})  [TRACE] %yellow(%mdc{trace_id})  [SPAN] %yellow(%mdc{span_id})  [FLAGS] %yellow(%mdc{trace_flags}) - %message %n"
  level:
    com.example.app: TRACE

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  cache:
    type: redis

  redis:
    host: redis
    port: 6379
