server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

storage:
  trace:
    backend: local
    wal:
      path: /etc/tempo/wal
    local:
      path: /etc/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

metrics_generator:
  storage:
    path: /etc/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

overrides:
  metrics_generator_processors: [ service-graphs, span-metrics ]