server:
  http_listen_port: 3200

storage:
  trace:
    backend: local
    wal:
      path: /etc/tempo/wal
    local:
      path: /etc/tempo/blocks

overrides:
  metrics_generator_processors: [ service-graphs, span-metrics ]